name: github pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y graphviz cargo

          cargo install mdbook --vers 0.4.9

          cd /tmp
          git clone https://github.com/dylanowen/mdbook-graphviz/
          cd mdbook-graphviz

          cargo build
          cargo install --force --path .

          cd ${{ github.workspace }}/

      - name: Build
        run: mdbook build

      # - run: docker run --rm -v $(pwd):/data -u $(id -u):$(id -g) pitop/mdbook mdbook build

      - name: Push
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./book
